### ISSUE TITLE
Testing the Issues tab and asking a question.

### ISSUE THREAD

**Issue by ghost** [ephemerant/C346-Roguelike#1]
Do you think that the player should only spawn within rooms? I personally think it'll look weird if the player is plopped in the middle of a hallway.

**Comment by ephemerant** [comment]
Yeah, I would think that players, monsters, items, and exits should only spawn in rooms.

Maybe we could have specific things such as traps, obstacles (Sudowoodo!), etc that only spawn in hallways.
