### ISSUE TITLE
To-Do List (10/29)

### ISSUE THREAD

**Issue by ephemerant** [ephemerant/C346-Roguelike#16]
##### General to-do list that I will peck away at (if no-one gets to these items):
- Basic enemy interaction (i.e. bump them, and they die)
- Combat interrupts movement
- Different enemy types
- More random enemy placement
- Bones on enemy "death"
- Prevent stairs from being spawned right next to doors
- Basic enemy animation
- Damage/death sounds
- Clean/refactor system, and set up test cases

Feel free to comment and claim any of these. I'll put them up on Trello, as well.

**Comment by ghost** [comment]
I accepted quite a few for me to be working on over the next week.

kind of like a sprint

**Comment by ghost** [comment]
Man, I really like Trello. So easy to organize the Todo-list.
