### ISSUE TITLE
Trello Page

### ISSUE THREAD

**Issue by ephemerant** [ephemerant/C346-Roguelike#4]
https://trello.com/b/XISltL05/c346-roguelike

I'm thinking this might make organizing everything easier.

If you could make an account and post what email you used here, I can invite you to be able to edit the Trello "board."

**Comment by jimbobmaggot** [comment]
srumpel@ius.edu

**Comment by jrlytle** [comment]
Hey, I just signed up under the email address jrlytle06@gmail.com.

**Comment by ghost** [comment]
I just signed up with cmorphis@umail.iu.edu
Turns out my normal email is so full that it is hard to find your emails. HA
