### ISSUE TITLE
Latest Version / Test Site

### ISSUE THREAD

**Issue by ephemerant** [ephemerant/C346-Roguelike#6]
I have it hosted on my VPS: http://www.clayton-mcguire.com/roguelike/

I was able to combine rot and Phaser, as discussed. I also have tile auto-joining implemented (i.e. the transitions between walls).

**Comment by ephemerant** [comment]
I will put it on here, but we should probably clean our repository a little first.

**Comment by ephemerant** [comment]
http://www.hostingpics.net/viewer.php?id=255431claytonsgame.png

One of my friends has too much free time...

**Comment by chrissexton** [comment]
:+1: nice!
